### ISSUE TITLE
aligning search result panels correctly

### ISSUE THREAD

**Issue by nicholascloud** [adamlucz90/RecordmateAngular#13]
The search result panels can be aligned correctly with a small adjustment to CSS.

``` css
#wishlist li {
    /* ... other styles omitted for brevity ...*/
    /*float: left;*/
    vertical-align: top;
}
```

First, each `<li>` tag is displayed as `inline-block`, which means they will flow together, one after the other, without having to be floated left. So remove the `float` rule from the CSS selector. This will solve the flow issue.

Second, to align the tops of each `<li>` element in each "row", add the `vertical-align: top` rule. The result is shown below.

![search-results-panels](https://cloud.githubusercontent.com/assets/513420/18856793/b3fbf4b2-8423-11e6-844f-4219d83e8896.png)
